Files for image-rotate benchmark
vhive-serverless/vSwarm pull request #1003
Opened 2024-07-19 12:43 UTC by KarthikL1729

Tested locally with docker-compose.

2024-07-19 13:32 UTC, dhschall commented on tools/relay/server
Don't put the binary in the PR

2024-07-19 13:32 UTC, dhschall commented on tools/relay/server.go
I don't think you want to have those changes in this PR as those are related to the profiling.

2024-07-19 13:34 UTC, KarthikL1729 commented on tools/relay/server
Oh I thought I had deleted it, will remove it.

2024-07-22 17:37 UTC, dhschall requested changes
Overall looks pretty good. Just some minor things. Also if you could use git lfs to track the image files that would be great

2024-07-22 17:37 UTC, dhschall commented on benchmarks/image-rotate/images/img1.jpg
Are the images added via git LFS?
Otherwise it would be better to avoid such a large file tracked by git.

2024-07-22 17:37 UTC, dhschall commented on benchmarks/image-rotate/images/img1.jpg
https://git-lfs.com/

2024-07-22 17:37 UTC, dhschall commented on benchmarks/image-rotate/images/img1.jpg
The grpcurl is also tracked via git lfs

2024-07-22 20:22 UTC, KarthikL1729 commented on .github/workflows/e2e-image-rotate.yml
>            ]
I think this was there in a previous version, it isn't there now.

2024-07-23 11:27 UTC, dhschall approved these changes
Looks good to me. Thank you @KarthikL1729 !

2024-07-23 11:27 UTC, merged