fix stock-knative runner.
vhive-serverless/vSwarm pull request #343
Opened 2022-11-11 14:47 UTC by shyamjesal

Signed-off-by: Shyam Jesal <s.jesalpura@gmail.com>

2022-11-11 16:35 UTC, ustiugov requested changes

2022-11-11 16:35 UTC, ustiugov commented on runner/scripts/setup-runner.sh
> +sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
please add a comment

2022-11-11 16:35 UTC, ustiugov commented on runner/scripts/install-konk.sh
>  echo -e "🔥 Installing Knative Eventing... \033[0m"
```suggestion
```

2022-12-16 14:35 UTC, dhschall approved these changes
Looks good to me!
Thanks for resolving

2022-12-16 14:39 UTC, dhschall commented
@ustiugov I guess this is resolved?

2022-12-16 14:44 UTC, merged