Init gptj benchmark
vhive-serverless/vSwarm pull request #740
Opened 2023-10-24 11:20 UTC by yankai14

Created gptj benchmark

For more information about the language model
https://huggingface.co/EleutherAI/gpt-j-6b

2023-10-31 11:18 UTC, lrq619 requested changes

2023-10-31 11:18 UTC, lrq619 commented on tools/relay/go.mod
This file should not be changed, if you want to upgrade some versions, please keep the updates minimal.

2023-10-31 11:18 UTC, lrq619 commented on tools/relay/go.sum
Same for this file, should not have such big modifications

2023-10-31 11:18 UTC, lrq619 commented on utils/tracing/go/go.mod
Same for this file, should not have such big modifications

2023-10-31 11:18 UTC, lrq619 commented on utils/tracing/go/go.sum
Same problem

2023-10-31 11:18 UTC, lrq619 commented on utils/tracing/integ-tests/client-server/goclient/go.mod
Same problem

2023-11-01 03:39 UTC, yankai14 commented on tools/relay/go.mod
I updated the go mod files (and hence go sum files too) because the previous version of [google.golang.org/grpc](http://google.golang.org/grpc) is causing an ambigious import error as explained below. The large changes is due to the additional dependencies the update needs.
https://github.com/aws-observability/aws-otel-collector/issues/926
Also I updated the modules to reflect the changes in vswarm-proto (grpcclient) that was merged previously.

2023-11-01 03:39 UTC, lrq619 approved these changes

2023-11-08 03:18 UTC, merged