Added files for compression benchmark
vhive-serverless/vSwarm pull request #998
Opened 2024-07-16 06:35 UTC by KarthikL1729

Added all the files for the compression benchmark. Tested with vSwarm-proto and docker-compose.

2024-07-16 12:50 UTC, KarthikL1729 commented on benchmarks/compression/python/server.py
> +LAMBDA = os.environ.get('IS_LAMBDA', 'no').lower() in ['true', 'yes', '1']
Shall I remove all the lambda related blocks?

2024-07-16 12:50 UTC, KarthikL1729 commented on benchmarks/compression/yamls/knative/kn-compression-python.yaml
> +            - --profile-function=true
Will remove it.

2024-07-18 11:00 UTC, dhschall requested changes
Looks all quite good. Just a minor change to make the test work

2024-07-18 11:06 UTC, KarthikL1729 commented on benchmarks/compression/yamls/docker-compose/dc-compression-python.yaml
> +    environment:
Oh I thought you meant the profile function flag alone, will remove all.

2024-07-18 11:11 UTC, KarthikL1729 commented on benchmarks/compression/yamls/docker-compose/dc-compression-python.yaml
> +    environment:
I think removing the value flag broke it before though

2024-07-18 11:22 UTC, KarthikL1729 commented on benchmarks/compression/yamls/docker-compose/dc-compression-python.yaml
> +    environment:
It does break the CI tests now as well, will leave it in.

2024-07-18 11:33 UTC, KarthikL1729 commented on .github/workflows/e2e-compression.yml
> +          ./tools/bin/grpcurl -plaintext -d '{"regenerate": "false"}' localhost:50050 compression.TODO
this seems to break the docker compose workflow, do I reset it?

2024-07-18 12:25 UTC, dhschall commented on .github/workflows/e2e-compression.yml
> +          ./tools/bin/grpcurl -plaintext -d '{"regenerate": "false"}' localhost:50000 compression-python.TODO
```suggestion
         ./tools/bin/grpcurl -plaintext localhost:50000 helloworld.Greeter.SayHello
```

2024-07-18 15:01 UTC, dhschall approved these changes
All good! 
Thank you @KarthikL1729 !

2024-07-18 15:01 UTC, merged